### ISSUE TITLE
Basic repository setup

### ISSUE THREAD

**Issue by yaaacii** [VolunteerOne/volunteer-one-app#7]

**Comment by dzeleniak** [comment]
# Overview
Added the package ```server```. 

### Router.go
The package contains _router.go_ which handles the creation of a gin Engine and contains all of our routes.

### Server.go
The file _server.go_ contains the function ```Init()``` which creates an instance of the router and runs it on the port specified in your .env file.

### Additional Changes
```main()``` is modified to use the new server package. The new initialization is brought down to one line in main 
``` go
func main() {
	server.Init()
}
```
